### ISSUE TITLE
Top priority: remove FresherNote example docs

### ISSUE THREAD

**Issue by brookeangel** [and-megan/Borrow-My-Backpack#5]
production_readme.md - replace with your own eventually
images in root directory regarding freshernote
API endpoints - replace this with your API endpoints A$AP
flux-cycles.md - replace this with your flux cycles A$AP
descriptions of phases - replace this with details of your phases A$AP

**Comment by and-megan** [comment]
Added these. Not sure if they're up to snuff, though.

**Comment by brookeangel** [comment]
Yay! Thanks Megan. Few quick notes: 

api-endpoints.md 
Sporting goods: 
- GET /api/sporting_goods/:id/show  - should just be api/sporting_goods/:id
  Users: 
  *PATCH /users - remove this one - you'll use your api/users api endpoint for this

Rest looks good! 😸

**Comment by and-megan** [comment]
updated the api-endpoints
