### ISSUE TITLE
More time needed

### ISSUE THREAD

**Issue by brookeangel** [and-megan/Borrow-My-Backpack#6]
- Recommend 3 days for phase 3 - everything takes longer than you'd think during final projects, and that's a lot of components to be building. You'll want to position/ do some light styling for things as you go, so it will take significantly longer than in class projects
- Recommend whole day for phase 6 - it looks like you have a search bar in your wireframes so make sure you build in time for this

**Comment by and-megan** [comment]
time has been increased, thanks for the rec.
